# config
cover: http://zhaoji223.bj.bcebos.com/BG.jpg?authorization=bce-auth-v1%2Fcc403c5d341a45edbc06fcd0798eef4c%2F2019-12-30T12%3A22%3A31Z%2F300%2Fhost%2F9ff505c9ae6b58f4a573f8d72df7f1f89752f1a8d3ad0d7e66f1f9d8f8a9951e
logo: http://zhaoji223.bj.bcebos.com/logo.png?authorization=bce-auth-v1%2Fcc403c5d341a45edbc06fcd0798eef4c%2F2019-12-30T12%3A22%3A42Z%2F300%2Fhost%2Fe55a1f0c288c1ab1a660cbfaec58ab6361c294d421661d9e94e254834a084a49
top_saying:
- title: 
- content: 
bottom_saying: 你好, 我叫西兰花.
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: 随笔
  works_url: /tags/%E9%9A%8F%E7%AC%94/
- works_name: book
  works_url: /tags/book/
- works_name: other
  works_url: /tags/other/
- works_name: http
  works_url: /tags/http/
- works_name: mobile
  works_url: /tags/mobile/

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: EL PSY CONGROO | cwj
  link: https://yo-cwj.com/
- name: 风之旅人 | 帅神
  link: https://di1shuai.com/
- name: Sean
  link: https://blog.csdn.net/u010416101
- name: Abel
  link: https://blog.csdn.net/u012373815

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
